site_name: "PHX Events Documentation"
site_url: "https://acefire6.github.io/phx_events/"
site_author: "Jethro Muller"
site_description: "Documentation for phx-events the Python 3 AsyncIO Phoenix Channels client"
repo_url: "https://github.com/AceFire6/phx_events/"
edit_uri: "edit/main/docs/"
use_directory_urls: true
copyright: "©2021 Jethro Muller"

theme:
  name: material

extra_css:
  - css/autodoc.css

markdown_extensions:
  - smarty
  - admonition
  - codehilite
  - toc:
      permalink: "#"
  - mkautodoc

plugins:
  - search
  - include-markdown
  - git-revision-date-localized
  - htmlproofer
  - ezlinks:
      warn_ambiguities: True
  - section-index
  - literate-nav:
      nav_file: NAV.md
