site_name: "PHX Events Documentation"
site_url: "https://acefire6.github.io/phx_events/"
site_author: "Jethro Muller"
site_description: "Documentation for phx-events the Python 3 AsyncIO Phoenix Channels client"
copyright: "©2021 Jethro Muller"

repo_url: "https://github.com/AceFire6/phx_events/"
edit_uri: "edit/main/docs/"

docs_dir: docs
use_directory_urls: true
theme:
  name: material
  custom_dir: docs/overrides
  palette:
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: blue
    accent: light blue
    toggle:
      icon: material/toggle-switch
      name: Switch to light mode
  - media: "(prefers-color-scheme: light)"
    scheme: default
    primary: indigo
    toggle:
      icon: material/toggle-switch-off-outline
      name: Switch to dark mode

extra:
  version:
    provider: mike

extra_css:
  - css/style.css

markdown_extensions:
  - smarty
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences
  - toc:
      permalink: "#"

plugins:
  - search
  - include-markdown
  - git-revision-date-localized
  - htmlproofer
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          selection:
            members: True
            docstring_style: "google"
            filters:
            - "!^_"  # exclude all members starting with _
            - "^__init__$"  # but always include __init__ modules and methods
          rendering:
            show_root_heading: True
            show_if_no_docstring: True
      watch:
        - phx_events/

  - ezlinks:
      warn_ambiguities: True
  - section-index
  - literate-nav:
      nav_file: NAV.md
