name: Vulnerability scan

on: [push, pull_request]
concurrency:
  cancel-in-progress: true
  group: debricked-${{ github.ref }}

jobs:
  vulnerabilities-scan:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: debricked/actions/scan@v1
      env:
        DEBRICKED_TOKEN: ${{ secrets.DEBRICKED_TOKEN }}
