name: Lint Pyton

on:
  pull_request:
    paths:
      - '**.py'

concurrency:
  group: lint-python-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint-python:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Get OS Version
      run: echo "os_version=$(lsb_release -sr)" >> "$GITHUB_ENV"

    - name: Cache pip
      id: cache-pip
      uses: actions/cache@v2
      with:
        path: |
          ${{ env.pythonLocation }}
          ~/.cache/pip
        key: ${{ runner.os }}-${{ env.os_version }}-${{ env.pythonLocation }}-${{ hashFiles('requirements/core.txt') }}-${{ hashFiles('requirements/dev.txt') }}
        restore-keys: |
          ${{ runner.os }}-${{ env.os_version }}-${{ env.pythonLocation }}-${{ hashFiles('requirements/core.txt') }}-
          ${{ runner.os }}-${{ env.os_version }}-${{ env.pythonLocation }}-

    - name: Install dependencies
      if: steps.cache-pip.outputs.cache-hit != 'true'
      run: |
        python -m pip install --upgrade pip setuptools wheel
        python -m pip install -r requirements/core.txt -r requirements/dev.txt

    - name: Flake8 Python Files
      run: flake8 --count --show-source --statistics .

    - name: iSort Python Files
      run: isort --check-only .

    - name: mypy Python Files
      run: mypy .
