name: Lint Github Workflows

on:
  pull_request:
    paths:
      - '.github/**.yml'

concurrency:
  group: lint-workflows-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint-workflows:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install shellcheck
        run: sudo apt-get install -y shellcheck

      - name: Install actionlint
        run: bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash)

      - name: Check workflow files with actionlint
        run: ./actionlint -ignore 'SC2129:' -color
